[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[tool.pyright]
typeCheckingMode = "standard"

[tool.ruff]
line-length = 60
